#!/bin/bash

cpath=$PWD
path=~/.vim

if [ ! -d "$path" ]; then
    git clone https://github.com/tpope/vim-pathogen.git "$path"
fi

#bundle
path="$path/bundle"
if [ ! -d "$path" ]; then
    mkdir "$path"
fi
cd "$path"

# NERDTree - explorer filesystem
git clone https://github.com/scrooloose/nerdtree.git

# Tag list - source code browser
sudo apt-get install exuberant-ctags
git clone https://github.com/vim-scripts/taglist.vim.git

# Lightline - status line/tab line
git clone https://github.com/itchyny/lightline.vim.git

# Supertab -  Perform all your vim insert mode completions with Tab 
git clone https://github.com/ervandew/supertab.git

# Molokai themes - theme
git clone https://github.com/tomasr/molokai.git

# Plugins for LANGUAGE PROGRAMMING
#
# Python jedi - autocomplete for python
git clone --recursive https://github.com/davidhalter/jedi-vim.git
#

#config file
path=~/.vimrc
cp -f "$cpath/vimrc" "$path"

#end#
